
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: localhost:5000/wisecow-app:latest  # Use the locally tagged image
          imagePullPolicy: Never  # Prevent Kubernetes from trying to pull the image
